export const TERMINAL_ERROR_CODES = {
  INVALID_UPSTREAM_MESSAGE: 'INVALID_UPSTREAM_MESSAGE',
  UPSTREAM_TERMINAL_ERROR: 'UPSTREAM_TERMINAL_ERROR',
  INVALID_TERMINAL_MESSAGE: 'INVALID_TERMINAL_MESSAGE',
  INVALID_TERMINAL_EVENT: 'INVALID_TERMINAL_EVENT',
  TERMINAL_WRITER_REQUIRED: 'TERMINAL_WRITER_REQUIRED',
  TERMINAL_BRIDGE_FAILED: 'TERMINAL_BRIDGE_FAILED',
  TERMINAL_CONNECT_FAILED: 'TERMINAL_CONNECT_FAILED',
  TERMINAL_STREAM_ERROR: 'TERMINAL_STREAM_ERROR',
} as const

export type TerminalErrorCode = (typeof TERMINAL_ERROR_CODES)[keyof typeof TERMINAL_ERROR_CODES]
