export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_NOT_READY: 'PROJECT_NOT_READY',
  SANDBOX_NOT_FOUND: 'SANDBOX_NOT_FOUND',
  SANDBOX_CREATION_FAILED: 'SANDBOX_CREATION_FAILED',
  SANDBOX_EXECUTION_FAILED: 'SANDBOX_EXECUTION_FAILED',
  PROJECT_CREATION_FAILED: 'PROJECT_CREATION_FAILED',
  PROJECT_SYNC_FAILED: 'PROJECT_SYNC_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export const DEFAULT_HTTP_ERROR_MESSAGES = {
  VALIDATION_ERROR: '请求参数校验失败',
  PROJECT_NOT_FOUND: '项目不存在',
  PROJECT_NOT_READY: '项目尚未完成初始化',
  SANDBOX_NOT_FOUND: '沙盒会话不存在',
  SANDBOX_CREATION_FAILED: '沙盒创建失败',
  SANDBOX_EXECUTION_FAILED: '沙盒执行失败',
  PROJECT_CREATION_FAILED: '项目创建失败',
  PROJECT_SYNC_FAILED: '项目同步失败',
  INTERNAL_SERVER_ERROR: '服务器内部错误',
  ROUTE_NOT_FOUND: '请求的资源不存在',
} as const satisfies Record<ErrorCode, string>
